seed: 0
output_dir_name: "pythia/seeds/opening seed {seed}"
task_config.prompts_file: "spd/experiments/lm/prompts/code_syntax_opening.txt"
---
seed: 0
output_dir_name: "pythia/seeds/combined seed {seed}"
task_config.prompts_file: "spd/experiments/lm/prompts/code_syntax_combined.txt"
---
seed: 1
output_dir_name: "pythia/seeds/opening seed {seed}"
task_config.prompts_file: "spd/experiments/lm/prompts/code_syntax_opening.txt"
---
seed: 1
output_dir_name: "pythia/seeds/combined seed {seed}"
task_config.prompts_file: "spd/experiments/lm/prompts/code_syntax_combined.txt"
