seed: 0
loss_metric_configs[ImportanceMinimalityLoss].coeff: 4e-4
---
seed: 1
loss_metric_configs[ImportanceMinimalityLoss].coeff: 4e-4
---
seed: 0
loss_metric_configs[ImportanceMinimalityLoss].coeff: 6e-4
---
seed: 1
loss_metric_configs[ImportanceMinimalityLoss].coeff: 6e-4
---
seed: 0
loss_metric_configs[ImportanceMinimalityLoss].coeff: 8e-4
---
seed: 1
loss_metric_configs[ImportanceMinimalityLoss].coeff: 8e-4
